// <auto-generated />
using System;
using FixerMovie.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FixerMovie.Migrations
{
    [DbContext(typeof(FixerMovieContext))]
    [Migration("20190401070942_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("FixerMovie.Models.Movie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("adult");

                    b.Property<string>("original_title");

                    b.Property<string>("overview");

                    b.Property<double>("popularity");

                    b.Property<string>("poster_path");

                    b.Property<DateTime>("release_date");

                    b.Property<int>("runtime");

                    b.Property<string>("title");

                    b.Property<double>("vote_average");

                    b.Property<int>("vote_count");

                    b.HasKey("id");

                    b.ToTable("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
